// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CalendarController from "./calendar_controller"
application.register("calendar", CalendarController)

import DaterangepickerController from "./daterangepicker_controller"
application.register("daterangepicker", DaterangepickerController)

import FormElementController from "./form_element_controller"
application.register("form-element", FormElementController)

import FormRefreshController from "./form_refresh_controller"
application.register("form-refresh", FormRefreshController)

import Hello2Controller from "./hello2_controller"
application.register("hello2", Hello2Controller)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import IndeterminateCheckboxController from "./indeterminate_checkbox_controller"
application.register("indeterminate-checkbox", IndeterminateCheckboxController)

import ModalsController from "./modals_controller"
application.register("modals", ModalsController)

import NotificationsModalController from "./notifications_modal_controller"
application.register("notifications-modal", NotificationsModalController)

import SearchFormController from "./search_form_controller"
application.register("search-form", SearchFormController)

import SlimController from "./slim_controller"
application.register("slim", SlimController)

import SortableController from "./sortable_controller"
application.register("sortable", SortableController)

import ThongkeController from "./thongke_controller"
application.register("thongke", ThongkeController)

import VanbanController from "./vanban_controller"
application.register("vanban", VanbanController)
